### ISSUE TITLE
Please add a license file, a screen shot and consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [firefoxic/firefoxic-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name `zsh-theme` is awfully generic. Please consider renaming it to something descriptive, or even just name it `firefoxic` after the plugin file.

I also prefer to add themes with screen shots in their readme so that users can see what they look like without having to install them.

Finally, please add a license file, some people won't use any code that doesn't have a license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by firefoxic** [comment]
Hi!

I didn't think anyone would need this fork. So I didn't do anything with it at first.

Now I added readme and license. And updated the repository name.

Any other recommendations?
